#!/usr/bin/env bash
# Create the same synthetic org chart platform/scripts/seed_synthetic_ad.py
# uses to backfill AD attributes, as real accounts in this stack's Samba4
# DC. Nothing seeds automatically otherwise -- see README.md "Seeding
# synthetic accounts", which this replaces with a loop.
#
# Keep DEPARTMENTS/TEAMS below in sync with SYNTHETIC_ORG_CHART in
# platform/scripts/seed_synthetic_ad.py -- they describe the same fixture
# org chart in two languages, not two designs.
#
# Requires the stack already running: docker compose up -d (see README.md).
#
# Usage: ./create_synthetic_users.sh [count]
set -euo pipefail
cd "$(dirname "$0")/.."

COUNT="${1:-8}"
COMPOSE="docker compose exec -T samba-ad-dc"

DEPARTMENTS=(NOC NOC SRE SRE)
TEAMS=(noc-shift-a noc-shift-b sre-platform sre-network)

gen_password() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 20; }

OUTPUT="synthetic-users.env"
echo "# Generated by create_synthetic_users.sh -- gitignored, do not commit." >"$OUTPUT"

created=0
for ((i = 0; i < COUNT; i++)); do
	slot=$((i % ${#TEAMS[@]}))
	login="ad-synthetic-$(printf '%03d' "$i")"
	department="${DEPARTMENTS[$slot]}"
	team="${TEAMS[$slot]}"
	password="$(gen_password)"

	if $COMPOSE samba-tool user create "$login" "$password" \
		--given-name="Synthetic" --surname="$team" --department="$department"; then
		$COMPOSE samba-tool group addmembers "Domain Users" "$login"
		{
			echo "# $login / $department/$team"
			echo "AD_SYNTHETIC_$(printf '%03d' "$i")_PASSWORD=$password"
		} >>"$OUTPUT"
		echo "$login: created ($department/$team)"
		created=$((created + 1))
	else
		echo "$login: FAILED (already exists?)" >&2
	fi
done

chmod 600 "$OUTPUT"
echo "$created/$COUNT created. Passwords written to $OUTPUT"
