#!/usr/bin/env bash
# Create the same synthetic org chart platform/scripts/seed_synthetic_ad.py
# uses to backfill AD attributes, as real accounts in this stack's Samba4
# DC. Nothing seeds automatically otherwise -- see README.md "Seeding
# synthetic accounts", which this replaces with a loop.
#
# Keep DEPARTMENTS/TEAMS below in sync with SYNTHETIC_ORG_CHART in
# platform/scripts/seed_synthetic_ad.py -- they describe the same fixture
# org chart in two languages, not two designs.
#
# Requires the stack already running: docker compose up -d (see README.md).
#
# Usage: ./create_synthetic_users.sh [count]
set -euo pipefail
cd "$(dirname "$0")/.."

COUNT="${1:-8}"
COMPOSE="docker compose exec -T samba-ad-dc"

DEPARTMENTS=(NOC NOC SRE SRE)
TEAMS=(noc-shift-a noc-shift-b sre-platform sre-network)

# `|| true` matters here: under `set -o pipefail` above, `head -c 20`
# closing the pipe early can send `tr` a SIGPIPE, which pipefail then
# reports as the pipeline failing (exit 141) even though head already
# captured the bytes it needed -- confirmed live: this crashed the script
# deterministically once it was looped 8x (each call is another roll of
# the same race) after gen-env.sh's identical pattern had been getting
# lucky every time it ran before now.
gen_password() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 20 || true; }

OUTPUT="synthetic-users.env"
echo "# Generated by create_synthetic_users.sh -- gitignored, do not commit." >"$OUTPUT"

created=0
for ((i = 0; i < COUNT; i++)); do
	slot=$((i % ${#TEAMS[@]}))
	login="ad-synthetic-$(printf '%03d' "$i")"
	department="${DEPARTMENTS[$slot]}"
	team="${TEAMS[$slot]}"
	password="$(gen_password)"

	# --surname must be unique per user: Samba's CN is given-name+surname,
	# and with only 4 teams cycling across up to 8+ users, two users
	# sharing a team (e.g. #0 and #4, both noc-shift-a) would otherwise
	# collide on the exact same CN despite having different logins --
	# confirmed live ("Entry CN=Synthetic noc-shift-a ... already exists").
	# No explicit "Domain Users" group add either: Samba assigns every new
	# user that group as their primaryGroupID automatically at creation
	# time; adding them too is redundant and Samba rejects it -- also
	# confirmed live ("member ... already set via primaryGroupID 513").
	if $COMPOSE samba-tool user create "$login" "$password" \
		--given-name="Synthetic" --surname="$team $(printf '%03d' "$i")" --department="$department"; then
		{
			echo "# $login / $department/$team"
			echo "AD_SYNTHETIC_$(printf '%03d' "$i")_PASSWORD=$password"
		} >>"$OUTPUT"
		echo "$login: created ($department/$team)"
		created=$((created + 1))
	else
		echo "$login: FAILED (already exists?)" >&2
	fi
done

chmod 600 "$OUTPUT"
echo "$created/$COUNT created. Passwords written to $OUTPUT"
