"""Create real TrueConf Server accounts for the same synthetic org chart
seed_synthetic_ad.py uses to backfill AD attributes, so a batch of test
users exists to log in through /v1/auth/login and immediately resolve to a
department/team.

TrueConf Server's user-management endpoint isn't fixed across versions
(same caveat as app/identity/oauth_client.py's userinfo path). This targets
the `POST /api/v3.11/users` shape documented in
https://github.com/TrueConf/TrueConf-Server-API-examples — confirm against
your server's own /api/v4/docs/ before pointing this at anything but a
throwaway pilot instance; override the path with
TRUECONF_ADMIN_API_USERS_PATH if it differs.

Requires TRUECONF_BASE_URL (already used by app/identity/oauth_client.py)
and TRUECONF_ADMIN_API_TOKEN — a personal/admin API token generated through
the server's control panel (Settings -> API), distinct from the OAuth2 app
used for end-user login. Generated passwords are written to
scripts/synthetic-trueconf-users.env (matches the repo's `*.env` gitignore
rule) and never printed to stdout.

    cd platform && python -m scripts.create_trueconf_users [--count N]
"""
import argparse
import asyncio
import os
import secrets
from pathlib import Path

import httpx

from scripts.seed_synthetic_ad import SYNTHETIC_ORG_CHART

DEFAULT_USERS_PATH = "/api/v3.11/users"
OUTPUT_PATH = Path(__file__).parent / "synthetic-trueconf-users.env"


def _generate_password() -> str:
    return secrets.token_urlsafe(18)


def _build_user(index: int, slot: dict) -> tuple[str, str, dict]:
    login = f"ad-synthetic-{index:03d}"
    password = _generate_password()
    return login, password, {
        "login_name": login,
        "first_name": "Synthetic",
        "last_name": slot["team"],
        "display_name": f"Synthetic {slot['team']} {index:03d}",
        "password": password,
        "department": slot["department"],
    }


async def main(count: int) -> None:
    base_url = os.environ["TRUECONF_BASE_URL"].rstrip("/")
    token = os.environ["TRUECONF_ADMIN_API_TOKEN"]
    path = os.environ.get("TRUECONF_ADMIN_API_USERS_PATH", DEFAULT_USERS_PATH)

    lines = ["# Generated by create_trueconf_users.py -- gitignored, do not commit.\n"]
    created = 0

    async with httpx.AsyncClient(timeout=10) as client:
        for index in range(count):
            slot = SYNTHETIC_ORG_CHART[index % len(SYNTHETIC_ORG_CHART)]
            login, password, user = _build_user(index, slot)
            response = await client.post(
                f"{base_url}{path}",
                headers={"Authorization": f"Bearer {token}"},
                json=user,
            )
            if response.status_code >= 400:
                print(f"{login}: FAILED ({response.status_code}) {response.text[:200]}")
                continue
            lines.append(f"# {login} / {slot['team']}\nTRUECONF_SYNTHETIC_{index:03d}_PASSWORD={password}\n")
            print(f"{login}: created ({slot['department']}/{slot['team']})")
            created += 1

    OUTPUT_PATH.write_text("".join(lines))
    OUTPUT_PATH.chmod(0o600)
    print(f"{created}/{count} created. Passwords written to {OUTPUT_PATH}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--count", type=int, default=8, help="number of synthetic accounts to create")
    args = parser.parse_args()
    asyncio.run(main(args.count))
